name: Run test suite
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v ./...
      - name: Test Echo example
        run: go test -v ./examples/echo
      - name: Test Fiber example
        run: go test -v ./examples/fiber
      - name: Test Gin example
        run: go test -v ./examples/gin
